### PR TITLE
Remove unnecessary brew packages

### PR DESCRIPTION
**Pull request by jazzsequence**
Arguably Composer and some of the other packages don't need to be brewed and just add lag time to the `brew bundle install`

### CODE REVIEW

**Review by jspellman814 — APPROVED** [review]
:shipit:

**Review by greg-1-anderson — APPROVED** [review]

**Comment by jazzsequence** [comment]
It looks like I don't have merge access on this repository, so I can't actually merge this PR. @greg-1-anderson can you do it or give me access? Maybe `cms-ecosystems` isn't an owner?

**Comment by namespacebrian** [comment]
Sorry this got missed for so long @jazzsequence .. merging now

**Comment by jazzsequence** [comment]
Thanks @namespacebrian !

**Pull request merged**
