### PR TITLE
[BUGS-4289] Call old_error_cb like apm did

### PR DESCRIPTION
**Pull request by namespacebrian**
https://github.com/pantheon-systems/apm/blob/pantheon/apm.c#L334

Our method doesn't receive a `format` argument so I didn't attempt to pass one on.. compiling this locally to make sure it's not broken in obvious ways

### CODE REVIEW

**Comment by namespacebrian** [comment]
Except possibly the last one, none of these seem related to this change..
```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Test open_basedir configuration [tests/security/open_basedir_scandir.phpt]
Bug #50005 (Throwing through Reflection modified Exception object makes segmentation fault) [Zend/tests/bug50005.phpt]
Bug #64821 Custom Exceptions crash when internal properties overridden (variation 1) [Zend/tests/bug64821.1.phpt]
Bug #64821 Custom Exceptions crash when internal properties overridden (variation 3) [Zend/tests/bug64821.3.phpt]
Bug #79514 (Memory leaks while including unexistent file) [Zend/tests/bug79514.phpt]
Test fgetc() function : usage variations - write only modes (Bug #42036) [ext/standard/tests/file/fgetc_variation3.phpt]
Test fgets() function : usage variations - write only modes (Bug #42036) [ext/standard/tests/file/fgets_variation1.phpt]
Test fread() function : usage variations - read some/all chars, write only mode (Bug #42036) [ext/standard/tests/file/fread_variation2.phpt]
Test fread() function : usage variations - read beyond file size, write only mode [ext/standard/tests/file/fread_variation4.phpt]
mkdir(dir, 0777) tests [ext/standard/tests/file/mkdir-002.phpt]
php://fd wrapper: invalid file descriptor [ext/standard/tests/file/php_fd_wrapper_04.phpt]
Bug #78323 Test exit code and error message for invalid parameters [sapi/cgi/tests/bug78323.phpt]
```

**Comment by greg-1-anderson** [comment]
Do all of the tests pass without this change? (Perhaps a rhetorical question, as we assume they should.)

**Comment by namespacebrian** [comment]
> Do all of the tests pass without this change? (Perhaps a rhetorical question, as we assume they should.)

currently running with `remote_error_monitor` not included at all, then i will run with it, but without this change.

**Comment by namespacebrian** [comment]
Fewer tests fail without `remote_error_monitor` included at all... :/

```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Test stream_isatty with redirected STDERR [tests/output/stream_isatty_err.phpt]
Test stream_isatty with redirected STDIN/STDERR [tests/output/stream_isatty_in-err.phpt]
mkdir(dir, 0777) tests [ext/standard/tests/file/mkdir-002.phpt]
php://fd wrapper: invalid file descriptor [ext/standard/tests/file/php_fd_wrapper_04.phpt]
Bug #78323 Test exit code and error message for invalid parameters [sapi/cgi/tests/bug78323.phpt]
```

**Comment by namespacebrian** [comment]
~2400 tests failed with `remote_error_monitor` without the change in this PR...

Summary: https://pastebin.com/ZcNXD5d8

**Comment by namespacebrian** [comment]
Oops.. I didn't mean to include the `Brewfile` changes in this PR.  They're changes that should be made but unrelated to BUGS-4289... I must've `git add` and `git commit -am` again....

**Comment by namespacebrian** [comment]
Tested this with a tagged deploy and error messages are showing up in `php-error.log`

**Review by greg-1-anderson — APPROVED** [review]

**Review by jspellman814 — APPROVED** [review]

**Pull request merged**
